### ISSUE TITLE
Installing is slow, possible to do multi-threaded?

### ISSUE THREAD

**Issue by albinahlback** [gap-actions/setup-cygwin#12]
Takes about 2 minutes to install Cygwin suited for FLINT on Github Actions. With all of the default packages, it takes about 3-4 minutes.

Is it possible to download multiple files at a time and extract them multithreaded?

**Comment by albinahlback** [comment]
Not very important, so if this is not really feasible, feel free to close.

**Comment by albinahlback** [comment]
Perhaps it's not possible to obtain a much faster extraction, which is the most time consuming part, as that's a lot of IO.

**Comment by ChrisJefferson** [comment]
Unfortunately, installing happens via the cygwin installer, so any improvements in performance would have to be added to the cygwin installer (I just checked and there isn't any obvious way to make it go in parallel).

**Comment by albinahlback** [comment]
Okay! Thanks for this answer!
